export const IS_CREATE_CLIENT = "IS_CREATE_CLIENT";
export const CLIENT_LIST = "CLIENT_LIST";
export const CLIENT_DELETED = "CLIENT_DELETED";
export const AFTER_UPDATE_CLIENT = "AFTER_UPDATE_CLIENT";
export const IS_UPDATE_CLIENT = "IS_UPDATE_CLIENT";
export const IS_PAY_CLIENT = "IS_PAY_CLIENT";
export const IS_PAID_CLIENT = "IS_PAID_CLIENT";
